# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Dinamyc_titanic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Din_titanic_controller import Din_titanic
from Views.Insertar_titanic import Ui_insert_titanic
from Views.Search1 import Ui_search1
from Views.Eliminar import Ui_Delete
#from Views.Select_csv import Ui_Form


class Ui_Dinamyc_titanic(object):
    def __init__(self, parent):
        self.parent = parent
        self.connect = Din_titanic(self,"titanic")
    def setupUi(self, Dinamyc_titanic):
        Dinamyc_titanic.setObjectName("Dinamyc_titanic")
        Dinamyc_titanic.resize(559, 377)
        self.centralwidget = QtWidgets.QWidget(Dinamyc_titanic)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 100, 116, 241))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_insert = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_insert.setObjectName("btn_insert")
        self.gridLayout_4.addWidget(self.btn_insert, 0, 0, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout_4.addWidget(self.btn_delete, 2, 0, 1, 1)
        self.btn_show = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_show.setObjectName("btn_show")
        self.gridLayout_4.addWidget(self.btn_show, 3, 0, 1, 1)
        self.btn_back = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout_4.addWidget(self.btn_back, 4, 0, 1, 1)
        self.btn_search1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_search1.setObjectName("btn_search1")
        self.gridLayout_4.addWidget(self.btn_search1, 1, 0, 1, 1)
        self.titulo = QtWidgets.QTextBrowser(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(140, 10, 411, 81))
        self.titulo.setObjectName("titulo")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 141, 341))
        self.textBrowser.setStyleSheet("background: rgba(6,187,176,1)")
        self.textBrowser.setOverwriteMode(False)
        self.textBrowser.setObjectName("textBrowser")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(150, 100, 401, 251))
        self.table.setObjectName("table")
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.textBrowser.raise_()
        self.layoutWidget_2.raise_()
        self.titulo.raise_()
        self.table.raise_()
        Dinamyc_titanic.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Dinamyc_titanic)
        self.statusbar.setObjectName("statusbar")
        Dinamyc_titanic.setStatusBar(self.statusbar)

        self.retranslateUi(Dinamyc_titanic)
        QtCore.QMetaObject.connectSlotsByName(Dinamyc_titanic)
#-----------------------------------------------EVENTS---------------------------------------------------------------------------------#
        self.x = self.btn_insert.clicked.connect(lambda:self.connect.call_insert(Ui_insert_titanic))
        self.x = self.btn_search1.clicked.connect(lambda:self.connect.call_search1(Ui_search1))
        self.x = self.btn_delete.clicked.connect(lambda:self.connect.call_eliminar(Ui_Delete))
        self.x = self.btn_back.clicked.connect(lambda:self.connect.call_back(self.parent, Dinamyc_titanic))

#---------------------------------------------END_EVENTS--------------------------------------------------------------------------------#
    def retranslateUi(self, Dinamyc_titanic):
        _translate = QtCore.QCoreApplication.translate
        Dinamyc_titanic.setWindowTitle(_translate("Dinamyc_titanic", "MainWindow"))
        self.btn_insert.setText(_translate("Dinamyc_titanic", "Insert"))
        self.btn_delete.setText(_translate("Dinamyc_titanic", "Delete"))
        self.btn_show.setText(_translate("Dinamyc_titanic", "Show all"))
        self.btn_back.setText(_translate("Dinamyc_titanic", "Back"))
        self.btn_search1.setText(_translate("Dinamyc_titanic", "Search value"))
        self.titulo.setHtml(_translate("Dinamyc_titanic", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; font-style:italic; text-decoration: underline;\">PROYECTO BASE DE DATOS 2</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Dinamyc_titanic", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">UTEC</span></p></body></html>"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dinamyc_titanic", "Id"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dinamyc_titanic", "Sobrevivio"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dinamyc_titanic", "Clase"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Dinamyc_titanic", "Apellido"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Dinamyc_titanic", "Nombre"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Dinamyc_titanic", "Sexo"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Dinamyc_titanic", "Edad"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("Dinamyc_titanic", "Sibsp"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("Dinamyc_titanic", "Parch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dinamyc_titanic = QtWidgets.QMainWindow()
    ui = Ui_Dinamyc_titanic()
    ui.setupUi(Dinamyc_titanic)
    Dinamyc_titanic.show()
    sys.exit(app.exec_())
