# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eliminar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Eliminar_controller import Eliminar


class Ui_Delete(object):
    def __init__(self,tabla,din_seq):
        self.connect = Eliminar(tabla,din_seq)
    def setupUi(self, Delete):
        Delete.setObjectName("Delete")
        Delete.resize(217, 193)
        self.titulo = QtWidgets.QTextBrowser(Delete)
        self.titulo.setGeometry(QtCore.QRect(0, 10, 211, 171))
        self.titulo.setStyleSheet("background: rgba(6,187,176,1)")
        self.titulo.setObjectName("titulo")
        self.layoutWidget = QtWidgets.QWidget(Delete)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 191, 64))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_valor = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_valor.setStyleSheet("")
        self.input_valor.setText("")
        self.input_valor.setObjectName("input_valor")
        self.gridLayout.addWidget(self.input_valor, 0, 1, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 1, 0, 1, 2)
        self.btn_valor = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_valor.setObjectName("btn_valor")
        self.gridLayout.addWidget(self.btn_valor, 0, 0, 1, 1)
#-----------------------------------------------EVENT-----------------------------------------------------------------------#
        self.x = self.btn_delete.clicked.connect(lambda: self.connect.Eliminar(self.input_valor.text(),Delete))
#---------------------------------------------END_EVENT---------------------------------------------------------------------#

        self.retranslateUi(Delete)
        QtCore.QMetaObject.connectSlotsByName(Delete)

    def retranslateUi(self, Delete):
        _translate = QtCore.QCoreApplication.translate
        Delete.setWindowTitle(_translate("Delete", "Form"))
        self.titulo.setHtml(_translate("Delete", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">UTEC</span></p></body></html>"))
        self.input_valor.setPlaceholderText(_translate("Delete", "valor"))
        self.btn_delete.setText(_translate("Delete", "Delete"))
        self.btn_valor.setText(_translate("Delete", "Valor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Delete = QtWidgets.QWidget()
    ui = Ui_Delete()
    ui.setupUi(Delete)
    Delete.show()
    sys.exit(app.exec_())
