# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Insertar_fifa.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Insertar_fifa_controller import Insertar_fifa


class Ui_insert_fifa(object):
    def __init__(self,tabla):
        self.connect = Insertar_fifa(tabla)
    def setupUi(self, insert_fifa):
        insert_fifa.setObjectName("insert_fifa")
        insert_fifa.resize(274, 749)
        self.titulo = QtWidgets.QTextBrowser(insert_fifa)
        self.titulo.setGeometry(QtCore.QRect(0, 10, 271, 731))
        self.titulo.setStyleSheet("background: rgba(6,187,176,1)")
        self.titulo.setObjectName("titulo")
        self.layoutWidget = QtWidgets.QWidget(insert_fifa)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 257, 660))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PAS = QtWidgets.QLabel(self.layoutWidget)
        self.PAS.setObjectName("PAS")
        self.gridLayout.addWidget(self.PAS, 8, 0, 1, 1)
        self.PHY = QtWidgets.QLabel(self.layoutWidget)
        self.PHY.setObjectName("PHY")
        self.gridLayout.addWidget(self.PHY, 11, 0, 1, 1)
        self.inp_awr = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_awr.setObjectName("inp_awr")
        self.inp_awr.addItem("")
        self.inp_awr.addItem("")
        self.inp_awr.addItem("")
        self.inp_awr.addItem("")
        self.inp_awr.addItem("")
        self.gridLayout.addWidget(self.inp_awr, 3, 1, 1, 1)
        self.OVR = QtWidgets.QLabel(self.layoutWidget)
        self.OVR.setObjectName("OVR")
        self.gridLayout.addWidget(self.OVR, 5, 0, 1, 1)
        self.inp_pac = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_pac.setObjectName("inp_pac")
        self.gridLayout.addWidget(self.inp_pac, 6, 1, 1, 1)
        self.SPD = QtWidgets.QLabel(self.layoutWidget)
        self.SPD.setObjectName("SPD")
        self.gridLayout.addWidget(self.SPD, 18, 0, 1, 1)
        self.KIC = QtWidgets.QLabel(self.layoutWidget)
        self.KIC.setObjectName("KIC")
        self.gridLayout.addWidget(self.KIC, 17, 0, 1, 1)
        self.inp_ovr = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_ovr.setObjectName("inp_ovr")
        self.gridLayout.addWidget(self.inp_ovr, 5, 1, 1, 1)
        self.Foot = QtWidgets.QLabel(self.layoutWidget)
        self.Foot.setObjectName("Foot")
        self.gridLayout.addWidget(self.Foot, 1, 0, 1, 1)
        self.inp_foot = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_foot.setObjectName("inp_foot")
        self.inp_foot.addItem("")
        self.inp_foot.addItem("")
        self.inp_foot.addItem("")
        self.gridLayout.addWidget(self.inp_foot, 1, 1, 1, 1)
        self.inp_position = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_position.setObjectName("inp_position")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.inp_position.addItem("")
        self.gridLayout.addWidget(self.inp_position, 2, 1, 1, 1)
        self.inp_dri = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_dri.setObjectName("inp_dri")
        self.gridLayout.addWidget(self.inp_dri, 9, 1, 1, 1)
        self.inp_sho = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_sho.setObjectName("inp_sho")
        self.gridLayout.addWidget(self.inp_sho, 7, 1, 1, 1)
        self.PAC = QtWidgets.QLabel(self.layoutWidget)
        self.PAC.setObjectName("PAC")
        self.gridLayout.addWidget(self.PAC, 6, 0, 1, 1)
        self.inp_def = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_def.setObjectName("inp_def")
        self.gridLayout.addWidget(self.inp_def, 10, 1, 1, 1)
        self.SM = QtWidgets.QLabel(self.layoutWidget)
        self.SM.setObjectName("SM")
        self.gridLayout.addWidget(self.SM, 12, 0, 1, 1)
        self.DWR = QtWidgets.QLabel(self.layoutWidget)
        self.DWR.setObjectName("DWR")
        self.gridLayout.addWidget(self.DWR, 4, 0, 1, 1)
        self.SHO = QtWidgets.QLabel(self.layoutWidget)
        self.SHO.setObjectName("SHO")
        self.gridLayout.addWidget(self.SHO, 7, 0, 1, 1)
        self.inp_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_id.setObjectName("inp_id")
        self.gridLayout.addWidget(self.inp_id, 0, 1, 1, 1)
        self.inp_pas = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_pas.setObjectName("inp_pas")
        self.gridLayout.addWidget(self.inp_pas, 8, 1, 1, 1)
        self.DRI = QtWidgets.QLabel(self.layoutWidget)
        self.DRI.setObjectName("DRI")
        self.gridLayout.addWidget(self.DRI, 9, 0, 1, 1)
        self.AWR = QtWidgets.QLabel(self.layoutWidget)
        self.AWR.setObjectName("AWR")
        self.gridLayout.addWidget(self.AWR, 3, 0, 1, 1)
        self.DIV = QtWidgets.QLabel(self.layoutWidget)
        self.DIV.setObjectName("DIV")
        self.gridLayout.addWidget(self.DIV, 13, 0, 1, 1)
        self.Id = QtWidgets.QLabel(self.layoutWidget)
        self.Id.setObjectName("Id")
        self.gridLayout.addWidget(self.Id, 0, 0, 1, 1)
        self.HAN = QtWidgets.QLabel(self.layoutWidget)
        self.HAN.setObjectName("HAN")
        self.gridLayout.addWidget(self.HAN, 15, 0, 1, 1)
        self.btn_insertar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_insertar.setObjectName("btn_insertar")
        self.gridLayout.addWidget(self.btn_insertar, 19, 0, 1, 2)
        self.inp_dwr = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_dwr.setObjectName("inp_dwr")
        self.inp_dwr.addItem("")
        self.inp_dwr.addItem("")
        self.inp_dwr.addItem("")
        self.inp_dwr.addItem("")
        self.inp_dwr.addItem("")
        self.gridLayout.addWidget(self.inp_dwr, 4, 1, 1, 1)
        self.REF = QtWidgets.QLabel(self.layoutWidget)
        self.REF.setObjectName("REF")
        self.gridLayout.addWidget(self.REF, 16, 0, 1, 1)
        self.Position = QtWidgets.QLabel(self.layoutWidget)
        self.Position.setObjectName("Position")
        self.gridLayout.addWidget(self.Position, 2, 0, 1, 1)
        self.POS = QtWidgets.QLabel(self.layoutWidget)
        self.POS.setObjectName("POS")
        self.gridLayout.addWidget(self.POS, 14, 0, 1, 1)
        self.DEF = QtWidgets.QLabel(self.layoutWidget)
        self.DEF.setObjectName("DEF")
        self.gridLayout.addWidget(self.DEF, 10, 0, 1, 1)
        self.inp_phy = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_phy.setObjectName("inp_phy")
        self.gridLayout.addWidget(self.inp_phy, 11, 1, 1, 1)
        self.inp_dri_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_dri_4.setObjectName("inp_dri_4")
        self.gridLayout.addWidget(self.inp_dri_4, 12, 1, 1, 1)
        self.inp_dri_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_dri_5.setObjectName("inp_dri_5")
        self.gridLayout.addWidget(self.inp_dri_5, 13, 1, 1, 1)
        self.inp_pos = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_pos.setObjectName("inp_pos")
        self.gridLayout.addWidget(self.inp_pos, 14, 1, 1, 1)
        self.inp_han = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_han.setObjectName("inp_han")
        self.gridLayout.addWidget(self.inp_han, 15, 1, 1, 1)
        self.inp_ref = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_ref.setObjectName("inp_ref")
        self.gridLayout.addWidget(self.inp_ref, 16, 1, 1, 1)
        self.inp_kic = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_kic.setObjectName("inp_kic")
        self.gridLayout.addWidget(self.inp_kic, 17, 1, 1, 1)
        self.inp_spd = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_spd.setObjectName("inp_spd")
        self.gridLayout.addWidget(self.inp_spd, 18, 1, 1, 1)
#-----------------------------------------------EVENT-----------------------------------------------------------------------#
        self.x = self.btn_insertar.clicked.connect(lambda: self.connect.Insertar(self.inp_id.text(),self.inp_foot.currentText(),self.inp_position.currentText(),
                                                                                self.inp_awr.currentText(), self.inp_dwr.currentText(), self.inp_ovr.text(),
                                                                                self.inp_pac.text(), self.inp_sho.text(),self.inp_pas.text(),self.inp_dri.text(),
                                                                                self.inp_def.text(),self.inp_phy.text(),self.inp_dri_4.text(),self.inp_dri_5.text(),
                                                                                self.inp_pos.text(),self.inp_han.text(),self.inp_ref.text(),self.inp_kic.text(),
                                                                                self.inp_spd.text(),insert_fifa))
#---------------------------------------------END_EVENT---------------------------------------------------------------------#
        self.retranslateUi(insert_fifa)
        QtCore.QMetaObject.connectSlotsByName(insert_fifa)

    def retranslateUi(self, insert_fifa):
        _translate = QtCore.QCoreApplication.translate
        insert_fifa.setWindowTitle(_translate("insert_fifa", "Form"))
        self.titulo.setHtml(_translate("insert_fifa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">UTEC</span></p></body></html>"))
        self.PAS.setText(_translate("insert_fifa", "PAS"))
        self.PHY.setText(_translate("insert_fifa", "Phy"))
        self.inp_awr.setItemText(0, _translate("insert_fifa", "Seleccionar opcion"))
        self.inp_awr.setItemText(1, _translate("insert_fifa", "High"))
        self.inp_awr.setItemText(2, _translate("insert_fifa", "Medium"))
        self.inp_awr.setItemText(3, _translate("insert_fifa", "Low"))
        self.inp_awr.setItemText(4, _translate("insert_fifa", "NA"))
        self.OVR.setText(_translate("insert_fifa", "OVR"))
        self.inp_pac.setPlaceholderText(_translate("insert_fifa", "0-97"))
        self.SPD.setText(_translate("insert_fifa", "Spd"))
        self.KIC.setText(_translate("insert_fifa", "Kic"))
        self.inp_ovr.setPlaceholderText(_translate("insert_fifa", "47 - 98"))
        self.Foot.setText(_translate("insert_fifa", "Foot"))
        self.inp_foot.setItemText(0, _translate("insert_fifa", "seleccionar opcion"))
        self.inp_foot.setItemText(1, _translate("insert_fifa", "R"))
        self.inp_foot.setItemText(2, _translate("insert_fifa", "L"))
        self.inp_position.setItemText(0, _translate("insert_fifa", "seleccionar opcion"))
        self.inp_position.setItemText(1, _translate("insert_fifa", "ST"))
        self.inp_position.setItemText(2, _translate("insert_fifa", "CF"))
        self.inp_position.setItemText(3, _translate("insert_fifa", "RW"))
        self.inp_position.setItemText(4, _translate("insert_fifa", "CAM"))
        self.inp_position.setItemText(5, _translate("insert_fifa", "LW"))
        self.inp_position.setItemText(6, _translate("insert_fifa", "CM"))
        self.inp_position.setItemText(7, _translate("insert_fifa", "LM"))
        self.inp_position.setItemText(8, _translate("insert_fifa", "RM"))
        self.inp_position.setItemText(9, _translate("insert_fifa", "CDM"))
        self.inp_position.setItemText(10, _translate("insert_fifa", "RWB"))
        self.inp_position.setItemText(11, _translate("insert_fifa", "LWB"))
        self.inp_position.setItemText(12, _translate("insert_fifa", "CB"))
        self.inp_position.setItemText(13, _translate("insert_fifa", "LB"))
        self.inp_position.setItemText(14, _translate("insert_fifa", "RB"))
        self.inp_position.setItemText(15, _translate("insert_fifa", "GK"))
        self.inp_dri.setPlaceholderText(_translate("insert_fifa", "0-97"))
        self.inp_sho.setPlaceholderText(_translate("insert_fifa", "0-96"))
        self.PAC.setText(_translate("insert_fifa", "PAC"))
        self.inp_def.setPlaceholderText(_translate("insert_fifa", "0-96"))
        self.SM.setText(_translate("insert_fifa", "SM"))
        self.DWR.setText(_translate("insert_fifa", "DWR"))
        self.SHO.setText(_translate("insert_fifa", "SHO"))
        self.inp_id.setPlaceholderText(_translate("insert_fifa", "ej: Pele"))
        self.inp_pas.setPlaceholderText(_translate("insert_fifa", "0-96"))
        self.DRI.setText(_translate("insert_fifa", "Dri"))
        self.AWR.setText(_translate("insert_fifa", "AWR"))
        self.DIV.setText(_translate("insert_fifa", "Div"))
        self.Id.setText(_translate("insert_fifa", "Id"))
        self.HAN.setText(_translate("insert_fifa", "Han"))
        self.btn_insertar.setText(_translate("insert_fifa", "Insertar"))
        self.inp_dwr.setItemText(0, _translate("insert_fifa", "Seleccionar opcion"))
        self.inp_dwr.setItemText(1, _translate("insert_fifa", "High"))
        self.inp_dwr.setItemText(2, _translate("insert_fifa", "Medium"))
        self.inp_dwr.setItemText(3, _translate("insert_fifa", "Low"))
        self.inp_dwr.setItemText(4, _translate("insert_fifa", "NA"))
        self.REF.setText(_translate("insert_fifa", "Ref"))
        self.Position.setText(_translate("insert_fifa", "Position"))
        self.POS.setText(_translate("insert_fifa", "Pos"))
        self.DEF.setText(_translate("insert_fifa", "Def"))
        self.inp_phy.setPlaceholderText(_translate("insert_fifa", "0-92"))
        self.inp_dri_4.setPlaceholderText(_translate("insert_fifa", "0-5"))
        self.inp_dri_5.setPlaceholderText(_translate("insert_fifa", "60-70"))
        self.inp_pos.setPlaceholderText(_translate("insert_fifa", "60-70"))
        self.inp_han.setPlaceholderText(_translate("insert_fifa", "60-70"))
        self.inp_ref.setPlaceholderText(_translate("insert_fifa", "60-70"))
        self.inp_kic.setPlaceholderText(_translate("insert_fifa", "60-70"))
        self.inp_spd.setPlaceholderText(_translate("insert_fifa", "30-45"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insert_fifa = QtWidgets.QWidget()
    ui = Ui_insert_fifa()
    ui.setupUi(insert_fifa)
    insert_fifa.show()
    sys.exit(app.exec_())
