# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Insertar_titanic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Insertar_titanic_controller import Insertar_titanic


class Ui_insert_titanic(object):
    def __init__(self,tabla):
        self.connect = Insertar_titanic(tabla)
    def setupUi(self, insert_titanic):
        insert_titanic.setObjectName("insert_titanic")
        insert_titanic.resize(264, 441)
        self.titulo = QtWidgets.QTextBrowser(insert_titanic)
        self.titulo.setGeometry(QtCore.QRect(0, 10, 261, 421))
        self.titulo.setStyleSheet("background: rgba(6,187,176,1)")
        self.titulo.setObjectName("titulo")
        self.layoutWidget = QtWidgets.QWidget(insert_titanic)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 241, 346))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.inp_sibsp = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_sibsp.setObjectName("inp_sibsp")
        self.gridLayout.addWidget(self.inp_sibsp, 7, 1, 1, 1)
        self.Edad = QtWidgets.QLabel(self.layoutWidget)
        self.Edad.setObjectName("Edad")
        self.gridLayout.addWidget(self.Edad, 6, 0, 1, 1)
        self.Id = QtWidgets.QLabel(self.layoutWidget)
        self.Id.setObjectName("Id")
        self.gridLayout.addWidget(self.Id, 0, 0, 1, 1)
        self.inp_sobrevivio = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_sobrevivio.setObjectName("inp_sobrevivio")
        self.inp_sobrevivio.addItem("")
        self.inp_sobrevivio.addItem("")
        self.inp_sobrevivio.addItem("")
        self.gridLayout.addWidget(self.inp_sobrevivio, 1, 1, 1, 1)
        self.Sexo = QtWidgets.QLabel(self.layoutWidget)
        self.Sexo.setObjectName("Sexo")
        self.gridLayout.addWidget(self.Sexo, 5, 0, 1, 1)
        self.Clase = QtWidgets.QLabel(self.layoutWidget)
        self.Clase.setObjectName("Clase")
        self.gridLayout.addWidget(self.Clase, 2, 0, 1, 1)
        self.inp_apellido = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_apellido.setObjectName("inp_apellido")
        self.gridLayout.addWidget(self.inp_apellido, 3, 1, 1, 1)
        self.parch = QtWidgets.QLabel(self.layoutWidget)
        self.parch.setObjectName("parch")
        self.gridLayout.addWidget(self.parch, 8, 0, 1, 1)
        self.inp_edad = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_edad.setObjectName("inp_edad")
        self.gridLayout.addWidget(self.inp_edad, 6, 1, 1, 1)
        self.sibsp = QtWidgets.QLabel(self.layoutWidget)
        self.sibsp.setObjectName("sibsp")
        self.gridLayout.addWidget(self.sibsp, 7, 0, 1, 1)
        self.Sobrevivio = QtWidgets.QLabel(self.layoutWidget)
        self.Sobrevivio.setObjectName("Sobrevivio")
        self.gridLayout.addWidget(self.Sobrevivio, 1, 0, 1, 1)
        self.btn_insertar = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_insertar.setObjectName("btn_insertar")
        self.gridLayout.addWidget(self.btn_insertar, 9, 0, 1, 2)
        self.inp_sexo = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_sexo.setObjectName("inp_sexo")
        self.inp_sexo.addItem("")
        self.inp_sexo.addItem("")
        self.inp_sexo.addItem("")
        self.gridLayout.addWidget(self.inp_sexo, 5, 1, 1, 1)
        self.inp_parch = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_parch.setObjectName("inp_parch")
        self.gridLayout.addWidget(self.inp_parch, 8, 1, 1, 1)
        self.Nombre = QtWidgets.QLabel(self.layoutWidget)
        self.Nombre.setObjectName("Nombre")
        self.gridLayout.addWidget(self.Nombre, 4, 0, 1, 1)
        self.inp_clase = QtWidgets.QComboBox(self.layoutWidget)
        self.inp_clase.setObjectName("inp_clase")
        self.inp_clase.addItem("")
        self.inp_clase.addItem("")
        self.inp_clase.addItem("")
        self.inp_clase.addItem("")
        self.gridLayout.addWidget(self.inp_clase, 2, 1, 1, 1)
        self.inp_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_nombre.setObjectName("inp_nombre")
        self.gridLayout.addWidget(self.inp_nombre, 4, 1, 1, 1)
        self.Apellido = QtWidgets.QLabel(self.layoutWidget)
        self.Apellido.setObjectName("Apellido")
        self.gridLayout.addWidget(self.Apellido, 3, 0, 1, 1)
        self.inp_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.inp_id.setObjectName("inp_id")
        self.gridLayout.addWidget(self.inp_id, 0, 1, 1, 1)
#-----------------------------------------------EVENT-----------------------------------------------------------------------#
        self.x = self.btn_insertar.clicked.connect(lambda: self.connect.Insertar(self.inp_id.text(),self.inp_sobrevivio.currentText(),self.inp_clase.currentText(),
                                                                                self.inp_apellido.text(), self.inp_nombre.text(), self.inp_sexo.currentText(),
                                                                                self.inp_edad.text(), self.inp_sibsp.text(),self.inp_parch.text(),insert_titanic))
#---------------------------------------------END_EVENT---------------------------------------------------------------------#
        self.retranslateUi(insert_titanic)
        QtCore.QMetaObject.connectSlotsByName(insert_titanic)

    def retranslateUi(self, insert_titanic):
        _translate = QtCore.QCoreApplication.translate
        insert_titanic.setWindowTitle(_translate("insert_titanic", "Form"))
        self.titulo.setHtml(_translate("insert_titanic", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">UTEC</span></p></body></html>"))
        self.inp_sibsp.setPlaceholderText(_translate("insert_titanic", "sibsp"))
        self.Edad.setText(_translate("insert_titanic", "Edad"))
        self.Id.setText(_translate("insert_titanic", "Id"))
        self.inp_sobrevivio.setItemText(0, _translate("insert_titanic", "seleccionar opcion"))
        self.inp_sobrevivio.setItemText(1, _translate("insert_titanic", "si"))
        self.inp_sobrevivio.setItemText(2, _translate("insert_titanic", "no"))
        self.Sexo.setText(_translate("insert_titanic", "Sexo"))
        self.Clase.setText(_translate("insert_titanic", "Clase"))
        self.inp_apellido.setPlaceholderText(_translate("insert_titanic", "Apellido"))
        self.parch.setText(_translate("insert_titanic", "parch"))
        self.inp_edad.setPlaceholderText(_translate("insert_titanic", "Edad"))
        self.sibsp.setText(_translate("insert_titanic", "sibsp"))
        self.Sobrevivio.setText(_translate("insert_titanic", "Sobrevivio"))
        self.btn_insertar.setText(_translate("insert_titanic", "Insertar"))
        self.inp_sexo.setItemText(0, _translate("insert_titanic", "Seleccione opcion"))
        self.inp_sexo.setItemText(1, _translate("insert_titanic", "Hombre"))
        self.inp_sexo.setItemText(2, _translate("insert_titanic", "Mujer"))
        self.inp_parch.setPlaceholderText(_translate("insert_titanic", "parch"))
        self.Nombre.setText(_translate("insert_titanic", "Nombre"))
        self.inp_clase.setItemText(0, _translate("insert_titanic", "seleccionar opcion"))
        self.inp_clase.setItemText(1, _translate("insert_titanic", "Alta"))
        self.inp_clase.setItemText(2, _translate("insert_titanic", "Media"))
        self.inp_clase.setItemText(3, _translate("insert_titanic", "Baja"))
        self.inp_nombre.setPlaceholderText(_translate("insert_titanic", "Nombre"))
        self.Apellido.setText(_translate("insert_titanic", "Apellido"))
        self.inp_id.setPlaceholderText(_translate("insert_titanic", "ej: 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insert_titanic = QtWidgets.QWidget()
    ui = Ui_insert_titanic()
    ui.setupUi(insert_titanic)
    insert_titanic.show()
    sys.exit(app.exec_())
