# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Principal_controller import Principal_controller



class Ui_main(object):
    def __init__(self, tabla,parent):
        self.Principal = Principal_controller(self)
        self.parent = parent
        self.tabla = tabla
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(441, 373)
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 131, 341))
        self.textBrowser.setStyleSheet("background: rgba(6,187,176,1)")
        self.textBrowser.setOverwriteMode(False)
        self.textBrowser.setObjectName("textBrowser")
        self.titulo = QtWidgets.QTextBrowser(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(130, 10, 301, 81))
        self.titulo.setObjectName("titulo")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 110, 179))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_seq = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_seq.setObjectName("btn_seq")
        self.gridLayout.addWidget(self.btn_seq, 0, 0, 1, 1)
        self.btn_dim = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_dim.setObjectName("btn_dim")
        self.gridLayout.addWidget(self.btn_dim, 1, 0, 1, 1)
        self.textBrowser.raise_()
        self.layoutWidget.raise_()
        self.titulo.raise_()
        main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
#--------------------------------------------------------------------------------------------------------------------------------------------#
        self.x = self.btn_seq.clicked.connect(lambda: self.Principal.change(self.tabla, main,"seq",self.parent))
        self.x = self.btn_dim.clicked.connect(lambda: self.Principal.change(self.tabla, main,"dim",self.parent))

#--------------------------------------------------------------end events---------------------------------------------------------------------#

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MainWindow"))
        self.textBrowser.setHtml(_translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">UTEC</span></p></body></html>"))
        self.titulo.setHtml(_translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; font-style:italic; text-decoration: underline;\">PROYECTO BASE DE DATOS 2</span></p></body></html>"))
        self.btn_seq.setText(_translate("main", "Sequential"))
        self.btn_dim.setText(_translate("main", "Dinamyc Hash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
