# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Select_csv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.Select_csv_controller import Select_csv_controller
from Views.Principal import Ui_main

class Ui_Form(object):
    def __init__(self):
        self.selection = Select_csv_controller(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(213, 186)
        self.titulo = QtWidgets.QTextBrowser(Form)
        self.titulo.setGeometry(QtCore.QRect(0, 10, 211, 171))
        self.titulo.setStyleSheet("background: rgba(6,187,176,1)")
        self.titulo.setObjectName("titulo")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 191, 64))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_titanic = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_titanic.setObjectName("btn_titanic")
        self.gridLayout.addWidget(self.btn_titanic, 0, 0, 1, 1)
        self.btn_cereal = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_cereal.setObjectName("btn_cereal")
        self.gridLayout.addWidget(self.btn_cereal, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

#--------------------------------------------------------------------------------------------------------------------------------------------#
        self.x = self.btn_cereal.clicked.connect(lambda: self.selection.change("btn_cereal", Ui_main, Form,Ui_Form))
        self.x = self.btn_titanic.clicked.connect(lambda: self.selection.change("btn_titanic", Ui_main, Form,Ui_Form))

#--------------------------------------------------------------end events---------------------------------------------------------------------#

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulo.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">UTEC</span></p></body></html>"))
        self.btn_titanic.setText(_translate("Form", "Titanic.csv"))
        self.btn_cereal.setText(_translate("Form", "Cereal.csv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
